ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
    name: validate Python code
    exclude: .*\.rst
  - id: check-case-conflict

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
  - id: ruff
    name: ruff (see https://docs.astral.sh/ruff/rules)
    args: [--fix]
  - id: ruff-format
    name: autoformat source code with ruff-format

- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v0.9.1
  hooks:
  - id: sphinx-lint

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.7
  hooks:
  - id: nbqa-check-ast
    name: validate Python notebooks
    exclude: notebooks/dispersion_solver.ipynb
  - id: nbqa-ruff
    name: ruff for notebooks (see https://docs.astral.sh/ruff/rules)
    args: [--fix, '--select=E,F,UP', '--ignore=E402,E501,E741,F401,F403,F405,F821']
